AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'app/channels/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'app/interactors/**/*.rb'
    - 'app/jobs/**/*.rb'
    - 'app/lib/**/*.rb'
    - 'app/mailers/**/*.rb'
    - 'app/serializers/**/*.rb'
    - 'app/workers/**/*.rb'
    - 'app/deserializers/**/*.rb'
    - 'app/controllers/**/*.rb'
    - 'app/models/**/*.rb'
    - 'app/services/**/*.rb'
    - '/lib/**/*.rb'
    - 'config/**/*.rb'
    - 'db/seeds.rb'
    - 'spec/**/*'
  Exclude:
    - '**/*.yml'
    - '__mocks__/**/*'
    - '__tests__/**/*'
    - '__js_test_config'
    - Gemfile*
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/import/*'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'spec/support/api/**/*'
    - 'spec/support/api/schemas/*.json'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'config/environments/production.rb'
    - 'config/initializers/devise.rb'
    - 'config/*.yml'
    - 'config/locales/*'
    - 'config/webpack/*'

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Max: 35

# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

Style/AndOr:
  # `and` and `or` banned only in conditionals (conditionals), or completely (always).
  EnforcedStyle: 'always'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'

Style/EmptyMethod:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/LineLength:
  Max: 140
  Exclude:
    - 'config/routes.rb'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'config/routes.rb'
    - 'Guardfile'
    - 'spec/**/*.rb'
    - 'lib/tasks/cypress.rake'

Layout/IndentFirstArrayElement:
  EnforcedStyle: 'consistent'
