/*
  converted with GD2md google drive add-on
  https://chrome.google.com/webstore/detail/gd2md-html/igffnbdfnodiaphfmfaiiaegmoljbghf?utm_source=permalink
  * GD2md-html version 1.0β11
  * Tue Apr 17 2018 11:13:17 GMT-0700 (PDT)
  * Source doc: https://docs.google.com/a/ideo.com/open?id=1vYYC1nEDoNiv_-dUEWma0hIOsi3Sqa6bRcldONjrwUM
*/

const touMarkdown = `
# TERMS OF USE

Please read these Terms of Use (**"Terms" **or** "TOU"**) carefully before using the Software (as defined below).  By using the Software, you are agreeing to be bound by the Terms. If you have entered into a separate software license or services agreement with IDEO for use of the Software or services, then the terms of that agreement shall controls if it conflicts with the Terms.

The Terms govern the use of the Software, which is licensed to the person using the Software ("You" or "User") by IDEO LP, a Delaware limited partnership, with a principal place of business at 150 Forest Avenue, Palo Alto, California 94301, USA (**"IDEO"**).



## DEFINITIONS
**"New Features"** means any feature(s) not in the Software that are developed and may be incorporated in the Software or Site by IDEO on license to You.

"**Personal Data**" means information which can be used to identify a person including but not limited to name, email address, images.

**"Site"** means the website owned and operated by IDEO that is accessed at [www.shape.space](https://www.shape.space) or any successor Site, and intended by the parties to incorporate the Platform to which these Terms apply.

**"Platform"** means the online platform owned by IDEO and used in or as part of the Site, known as "Shape."

"**Software**" means the Platform and all source code, object code, architecture, designs, functionality, content (excluding User Content), features, templates, and documentation or other websites embodied in and related to the Platform, as well as all uploads, updates and customisations to any of the foregoing, including New Features.

"**User Content**" means all copyrighted content created, or owned, by a User and incorporated on the Site including but not limited to postings and communication from and between Users of the Site.



## LICENSE; OWNERSHIP
**2.1  License; Restrictions.  **Subject to compliance with the Terms, IDEO grants to You during the Term, a personal, non-transferable, non-exclusive license, without right to sublicense, to: (i) access and use the Platform for the purposes necessary to access, register on and utilize the Siteincluding: making submissions and postings to the Site; using templates and other IDEO content available on the Site; form teams and communicate with other Users; recording and undertaking research.  The Software, including without limitation the Platform, is the proprietary property of IDEO.  You shall not, and shall not permit any third party to, use or copy the Software except as expressly permitted herein.  You shall not adapt, modify, disassemble, decompile or reverse engineer the Software in whole or in part or introduce any virus or trojan horse, software code or programs, which are intended to or are likely to be harmful or affect the functionality of the Software or Site, or let any third party do so, except only to the extent the foregoing are not permitted to be restricted under applicable law. All rights not expressly granted herein are retained by IDEO.  No right or license is granted or implied to You under any of IDEO's patents, copyrights, trademarks, trade names, service marks or other intellectual property rights beyond the rights set forth in the Terms.

**2.2  Ownership.  **IDEO retains all right, title and interest in and to the Software.  Title to and ownership of any modifications or customisations of the Software shall be held exclusively by IDEO. You grant IDEO the right and license to make, use, sell, reproduce, modify, sublicense, disclose, distribute and otherwise exploit error reports, corrections, and suggestions provided by You directly or indirectly (for example, in the reporting of faults) concerning the Software and modifications based thereon. You acknowledge that IDEO owns all intellectual property and other rights in any reports or other material generated using Analytics Data as defined herein. You agree to perform such acts, and execute and deliver such instruments and documents, and do all other things as may be reasonably necessary to evidence or perfect the rights of IDEO set forth in this Section 2.2.

**2.3  Use of Analytic Data.**  You acknowledge and grant IDEO the right to use, create, process, review, evaluate, copy, analyse AnalyticData. "Analytic Data" as used in these Terms means data generated by and in relation to the Software including but not limited to:



1.
Participation levels and general behavior patterns of Users by category


1.
Industry sector and occupation data of Users;


1.
Level and nature of collaboration between Users;


1.
Level and format of device of Users (such as desktop computer, mobile device);


1.
Time spent by Users on Site.


1.
Behaviour of Users on individual functions of the Software, and any feature of the Customer Site;


1.
Data related to User content (such as the effectiveness of the Software in facilitating User objectives and analysing return on investment)


1.
Trending topics among Users


1.
Impact of bugs or Software errors on User activity.
We use Analytic Data primarily for our internal purposes to improve IDEO products and services, tailor such services to Users, and to add to our innovation development and learnings.

Where Analytic Data is disclosed to or accessed by any third party (except IDEO subcontractors including third party providers of tools who may have access), (i) personally identifiable information will be anonymised; (ii) business information will be  de-identified, and aggregated.

**2.4. Personal Data on the Site.**

In addition to our use of Analytics Data, IDEO will process Your Personal Data in accordance with our [Privacy Policy](https://www.ideo.com/privacy) (as updated from time to time).

As part of your use of the Site and its features, you may receive Personal Data e.g from other Users, your own team members, employees and associates of IDEO, individuals involved in research of concepts and testing. You agree to comply with applicable privacy laws in relation to such Personal Data including but not limited to:



1.  Ensuring you have the legal right (such as consent) to post Personal Data on the Site;
1.  Using Personal Data only for the purposes authorized by the individual about whom the Personal Data relates;
1.  Only use Personal Data received by IDEO (including but not limited to research feedback materials which identify an individual such as name, images, video, voice recordings ("Feedback Materials") for your internal evaluation purposes related to the particular project, concept, product, or service about which You sought feedback from IDEO.
1.  Using Personal Data for legitimate purposes and for a duration which is necessary only;
1.  On request for deletion, copies or amendment of the Personal Data held, stored or posted by You on the Site (or obtained via the Site), to (i) inform IDEO of such requests; and (ii) to comply with such requests in accordance with applicable laws.

**2.5** **Acceptable Use Policy**

IDEO retains the right to review, edit or delete from the Site any User Content they, in their discretion as necessary, consider illegal, offensive, damaging to the reputation of IDEO or otherwise inappropriate, including disrupting the normal flow of the Site, participating in negative dialogue on the Site or otherwise acting in a manner that negatively affects other Users; posting any unsolicited chain letters, advertising, promotional materials, contests, or any other commercial or non-commercial solicitations.

IDEO does not assess or guarantee the quality or safety of any events or activities organized in connection with Users' participation on the Site and your decision to participate in any such events and communicate with Users of the Site is entirely at your own risk.

We have the right to investigate violations of this TOU or conduct that affects the Site. We may also consult and cooperate with law enforcement authorities and regulators regarding Users who violate the law.

You are solely responsible for all of Your communications and interactions with other Users of the site and with other persons with whom You communicate or interact as a result of Your use of the Site.



## LIABILITY.
**3.1  Site Liability; Intellectual Property Rights.**  You acknowledge and agree that IDEO does not control or dictate Your use of the Site (except as regards Section 2.5 of these TOU), including but not limited to your postings, your contributions, use of other user contributions to the Site, interaction with other Users, or individuals you contact as part of research activities on the Site.  Therefore, You agree to defend and indemnify IDEO, its employees, directors, contractors, and assigns from and against any claims, including reasonable legal and expert fees and costs incurred by IDEO in connection with Your use of the Software or Site, where a third party alleges (i) that it has been damaged by such use, or (ii) any claim of misappropriation or infringement by your use of the Site or Software (iii) any claim of infringement of Personal Data rights of any individual; (iv) any claim of third party intellectual property infringement  or breach of confidentiality due to User Content.



## WARRANTY DISCLAIMER; LIMITATION OF LIABILITY
EXCEPT AS MAY BE EXPRESSLY SET FORTH HEREUNDER, THE SOFTWARE IS PROVIDED "AS IS" AND IDEO MAKES NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS, OR FITNESS FOR A PARTICULAR PURPOSE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED.

IN NO EVENT SHALL IDEO BE LIABLE FOR ANY INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR INDIRECT DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION THOSE RELATING TO LOSS OF USE, INTERRUPTION OF BUSINESS AND/OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  IN NO EVENT SHALL IDEO'S AGGREGATE LIABILITY EXCEED $100,000.

NOTHING IN THE TERMS SHALL EXCLUDE OR RESTRICT IDEO'S LIABILITY FOR FRAUD, OR FOR DEATH OR PERSONAL INJURY TO THE OTHER PARTY RESULTING FROM IDEO'S NEGLIGENCE OR FOR ANY OTHER LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY LAW.



## TERM AND TERMINATION
**5.1  Term.**  The Terms shall remain in full force and effect until terminated as provided herein.

**5.2  Termination.**  Your license to use the Software may be terminated by IDEO in its sole discretion. Your right to use the Software will be terminated immediately by IDEO in the event You breach the license grant in Section 2.1.

**5.3  Effect of Termination. ** In the event the license granted to You to use the Software as provided hereunder  is terminated for any reason, (i) Your access to the Software may be restricted or withdrawn entirely; (ii) You must cease all activity on the Site which utilizes the Software.  Sections 2.2, 4, 6, 7, will survive any termination.



## MISCELLANEOUS
**6.1  Entire Agreement; No Waiver; Severability.** If any provision of these Terms is found to be invalid or unenforceable, such provision shall be severed from the Terms.

**6.2** **Amendment of Terms**. IDEO reserves the right to amend the Terms at its discretion without further notice or approval by You, except as required under applicable law. Your continued use of the Site following the posting of changes or modifications will constitute and confirm Your agreement to and acceptance of such changes or modifications. If You do not agree to the amended TOU, please discontinue using the Site. Because our services are evolving over time, we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.

**6.3  Governing Law; Jurisdiction; Legal Fees. **  The Terms, and any dispute or claim arising out of or in connection with the Terms and the Software, whether of a contractual or non-contractual nature, shall be governed by and construed in accordance with the laws of the State of California.  In any disputes or proceedings relating hereto (whether contractual or non-contractual in nature), the parties agree and hereby submit to the exclusive jurisdiction of the state and federal courts of Santa Clara County, California.

**6.4  Assignment.**  The relationship created between the parties hereto is that of independent contractors.  Nothing herein creates a relationship of employer and employee, principal and agent, partnership or the like between You, IDEO, or any of its affiliates or personnel.  Neither party will have authority to enter into any contract on behalf of the other.  IDEO may assign the Terms in the case of a merger, acquisition or corporate reorganization to a successor-in-interest of all or substantially all of IDEO's assets.

**6.5  Notices. ** Any notice You wish to give in accordance with the Terms shall be in writing and mailed or delivered to IDEO at:  General Counsel, 150 Forest Avenue, Palo Alto, California 94301, with an email copy to [legalnotice@ideo.com](mailto:legalnotice@ideo.com). Notices shall be deemed to have been duly given upon delivery when sent by express mail or certified mail, return receipt requested.

**6.6  Publicity.**  You shall not use IDEO's name, marks, or logos in relation to any product or service branding, packaging or advertising without IDEO's prior written consent.

`

export default touMarkdown
