production:
  adapter: <%= ENV.fetch('ACTION_CABLE_ADAPTER') { 'redis' } %>
  url: <%= ENV['REDIS_URL'] %>
development:
  adapter: <%= ENV.fetch('ACTION_CABLE_ADAPTER') { 'redis' } %>
  url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379' } %>
test:
  adapter: test
