#!/usr/bin/env bash
# We support all major Ruby versions. Please see our docs for a full list
# https://codeship.com/documentation/languages/ruby/

# DEBUG + include rvm
source ~/.bash_profile

# -------------
# NOTE: have to call Elastic setup directly in Codeship config otherwise ES server is inaccessible
# Start Java 8 for Elasticsearch 6
source $HOME/bin/jdk/jdk_switcher
jdk_switcher home oraclejdk8
jdk_switcher use oraclejdk8
# Start up ElasticSearch Version 6.2.0 on port 9333 (so it doesn't conflict with default)
export ELASTICSEARCH_VERSION=6.2.0
export ELASTICSEARCH_PORT=9333
\curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/elasticsearch.sh | bash -s
# ---------------------

# Setup nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install $(cat .nvmrc)
nvm use $(cat .nvmrc)
nvm alias default $(cat .nvmrc)
#
# Setup Yarn
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.1
export PATH="$HOME/.yarn/bin:$PATH"
source /home/rof/.bashrc
yarn install --frozen-lockfile
#
# Setup Ruby and gems
rvm use $(cat .ruby-version)
bundle config build.nokogiri --use-system-libraries
bundle install
# Get db ready
# Use postgres 9.6 -- docs: https://documentation.codeship.com/basic/databases/postgresql/
sed -i "s|5432|5436|" "config/database.yml"
bundle exec rake db:setup
bundle exec rake searchkick:reindex:all
