#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DIR=$(pwd)

git submodule init
git submodule update

if [ ! -f "$DIR/.env" ]; then
  echo "Missing env file $DIR/.env !"
  exit 1
fi

yarn install
bundle install
# setup runs db:create, db:schema:load and db:seed
bin/rails db:setup
# install git hooks
bundle exec lefthook install
script/override-post-checkout-hook
