#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DIR=$(pwd)

js_files=$(comm -23 <(git diff --cached --name-only --diff-filter=ACM) <(git diff --name-only) | grep -e '\.\(js\)x\?$')

set -e

if [ -n "$js_files" ]; then
  "$DIR"/node_modules/.bin/eslint --fix $js_files
  git add -f $js_files
fi
