#!/bin/sh

if [ "{$LEFTHOOK}" = "0" ]; then
	exit 0
fi

# added setup to prompt user for changes
exec < /dev/tty
echo "Do you want to proceed with lefthook scripts? y/n"
read -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
	exit 0
fi
echo ""
echo "running post-checkout..."
# -----

cmd="lefthook run post-checkout $@"

if lefthook >/dev/null 2>&1
then
  exec $cmd
elif bundle exec lefthook >/dev/null 2>&1
then
  bundle exec $cmd
elif npx lefthook >/dev/null 2>&1
then
  npx $cmd
else
  echo "Can't find lefthook in PATH"
fi
