#!/usr/bin/env bash

# We get authenticated using the HEROKU_API_TOKEN value
# You can generate a long-lived token using `heroku authorizations:create`

# Set the BASE_HOST and ACTION_CABLE_URL from the review app name
heroku config:set BASE_HOST=https://${HEROKU_APP_NAME}.herokuapp.com ACTION_CABLE_URL=wss://${HEROKU_APP_NAME}.herokuapp.com/cable REDIS_URL=${REDISCLOUD_URL} --app ${HEROKU_APP_NAME}

# Add the redirect URI for this review app to the whitelist of redirect URIs
rake network_api:application_add_redirect_uri
